---

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
  tags:
    - "role::reverseproxy"
    - "role::reverseproxy:install"
    - "role::reverseproxy:config"

- name: Install reverse proxy - Debian
  ansible.builtin.import_tasks: Debian.yml
  when: "ansible_facts.os_family == 'Debian'"
  tags:
    - "role::reverseproxy"
    - "role::reverseproxy:install"
    - "role::reverseproxy:config"

- name: Install reverse proxy - RedHat
  ansible.builtin.import_tasks: RedHat.yml
  when: "ansible_facts.os_family == 'RedHat'"
  tags:
    - "role::reverseproxy"
    - "role::reverseproxy:install"
    - "role::reverseproxy:config"
